CREATE TABLE TB_ENTRY(
  ID            BIGINT AUTO_INCREMENT NOT NULL,
  ENTRY_DATE    DATE          NOT NULL,
  CATEGORY_ID   BIGINT   NOT NULL,
  ACCOUNT_ID    BIGINT   NOT NULL,
  OPERATION     VARCHAR(10)   NOT NULL,
  PAYMENT_TYPE  VARCHAR(10)   NOT NULL,
  CARD_ID       BIGINT,
  VALUE_ENTRY   NUMBER(10, 2) NOT NULL,
  DISCOUNT      NUMBER(10, 2),
  OBSERVATION   VARCHAR(100),
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);