ALTER TABLE TB_ACCOUNT ADD CONSTRAINT FK_ACCOUNT FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(ID);
ALTER TABLE TB_ENTRY ADD CONSTRAINT FK_ENTRY_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(ID);
ALTER TABLE TB_ENTRY ADD CONSTRAINT FK_ENTRY_ACCOUNT FOREIGN KEY(ACCOUNT_ID) REFERENCES TB_ACCOUNT(ID);
ALTER TABLE TB_ENTRY ADD CONSTRAINT FK_ENTRY_CARD FOREIGN KEY(CARD_ID) REFERENCES TB_CARD(ID);