CREATE TABLE TB_ENTRY(
  ID            VARCHAR(255) NOT NULL,
  ENTRY_DATE    DATE          NOT NULL,
  CATEGORY_ID   VARCHAR(255)  NOT NULL,
  ACCOUNT_ID    VARCHAR(255)  NOT NULL,
  OPERATION     VARCHAR(10)   NOT NULL,
  PAYMENT_TYPE  VARCHAR(10)   NOT NULL,
  CARD_ID       VARCHAR(255),
  VALUE         NUMBER(10, 2) NOT NULL,
  DISCOUNT      NUMBER(10, 2),
  OBSERVATION   VARCHAR(100),
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);