ALTER TABLE TB_CATEGORY ADD CONSTRAINT CATEGORY_PK PRIMARY KEY (ID);
ALTER TABLE TB_ACCOUNT  ADD CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID);
--ALTER TABLE TB_CARD     ADD CONSTRAINT CARD_PK    PRIMARY KEY (ID);
--ALTER TABLE TB_ENTRY    ADD CONSTRAINT ENTRY_PK   PRIMARY KEY (ID);