ALTER TABLE TB_ACCOUNT ADD CONSTRAINT FK_ACCOUNT FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(ID);
ALTER TABLE TB_ENTRY ADD FOREIGN KEY(CATEGORY_ID) REFERENCES TB_CATEGORY(ID);
ALTER TABLE TB_ENTRY ADD FOREIGN KEY(ACCOUNT_ID) REFERENCES TB_ACCOUNT(ID);
ALTER TABLE TB_ENTRY ADD FOREIGN KEY(CARD_ID) REFERENCES TB_CARD(ID);